#!/usr/bin/env bash

# Function to get DNS information for a subdomain
get_dns_info() {
    local domain=$1
    local subdomain=$2
    local record_type=$3
    local destination=$(dig +short $subdomain.$domain $record_type | awk '{print $1}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if the correct number of arguments are provided
if [[ $# -eq 1 ]]; then
    domain=$1
    get_dns_info $domain www A
    get_dns_info $domain lb-01 A
    get_dns_info $domain web-01 A
    get_dns_info $domain web-02 A
elif [[ $# -eq 2 ]]; then
    domain=$1
    subdomain=$2
    get_dns_info $domain $subdomain A
else
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

