#!/usr/bin/env bash

global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon
	tune.ssl.default-dh-param 2048

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOTVptb/WCLpSyCK4CH1ytnefU2GyBe8YAr8/Z/Wq1LZLSfJbvwWkYkhbNrOV6ech5C+oia4tWXnVm+X/z9VdA25EYPMnhEi3j9QRUUS6EN5tt/Um/f+hZ2XFuAq7FC1h82Inify/PKj9z2A62cw7Z1stLgLP/4s1UskeW2ytiFnGvnzf2Q8yR2ej9XCiolh04vK2P2dvu97h71ar15DAY1gy6NT80+nClWfNYSZeX9CeQUPlkhC3U2qeGYOJQ+pswS07aus5eCXWYFjewHtMXvko07RjPxElbzQ4VnoVH8e0bet2UsbgLg5LA2zuE+FshGvHfwEk9CHsZfQMcAtGz root@67db5c3e97d6
   ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

frontend haproxy_balancer
	bind *:80
	bind *:443 ssl crt /etc/letsencrypt/live/www.emmanueldev247.tech/fullchain-key.pem
	redirect scheme https code 301 if !{ ssl_fc }
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
server 102680-web-01 35.175.135.59
server 102680-web-02 18.234.130.208
