#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update && sudo apt-get dist-upgrade -y
sudo apt-get -y install haproxy
sudo cp --backup=numbered /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo cp --backup=numbered /etc/default/haproxy /etc/default/haproxy.bak
sudo tee /etc/haproxy/haproxy.cfg << EOF
frontend http
  bind *:80
  mode http
  timeout client 30s
  timeout server 30s
  timeout connect 5s
  default_backend web_servers
backend web_servers
  mode http
  balance roundrobin
  timeout client 30s
  timeout server 30s
  timeout connect 5s
  server 102680-web-01 35.175.135.59
  server 102680-web-02 	18.234.130.208
EOF

# Enable Haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
